version: "3"
services:
  app:
    depends_on:
      - mongodb
    image: usuario/juegos
    ports:
      - 8080:8080
    build: ./practica3
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - web_net
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - web_net
volumes:
  mongodb:
networks:
  web_net:
      driver: bridge
